spring:
  data:
    redis:
      host: 192.168.0.2
      port: 6379
      password:   # 필요시
      database: 0
      timeout: 3000ms

      # Connection Pool 설정 (Lettuce 기본)
      lettuce:
        pool:
          max-active: 10 # 최대 커넥션 수
          max-idle: 10
          min-idle: 1
          max-wait: -1ms